fix NPE in case when none templated links appears in response JSON
ticketmaster-api/sdk-java pull request #25
Opened 2017-04-14 14:01 UTC by oleksiiBobko

2017-04-14 16:28 UTC, piclemx requested changes

2017-04-14 16:28 UTC, piclemx commented on discovery-model/src/main/java/com/ticketmaster/discovery/model/Page.java
> +      if ((templated != null) && templated) {
By preference, 
```java
if ( templated != null && templated)
```

2017-04-14 16:52 UTC, oleksiiBobko commented on discovery-model/src/main/java/com/ticketmaster/discovery/model/Page.java
> +      if ((templated != null) && templated) {
changed

2017-04-21 17:07 UTC, ledor473 commented
LGTM :+1:

2017-04-21 17:07 UTC, merged